#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2018-2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import datetime
import sys

# fake the ‘requests’ module to speed up imports:
sys.modules['requests'] = False

import astral

def parse_date(s):
    return datetime.datetime.strptime(s, '%Y-%m-%d').date()

try:
    import astral.geocoder
except ImportError:
    astral.geocoder = None
else:
    import astral.location

if astral.geocoder:
    # astral >= 2.0
    def get_location(name):
        db = astral.geocoder.database()
        locinfo = astral.geocoder.lookup(name, db)
        return astral.location.Location(locinfo)
else:
    # astral < 2.0
    def get_location(name):
        astro = astral.Astral()
        location = astro[name]
        location.midnight = location.solar_midnight
        location.noon = location.solar_noon
        return location

def main():
    ap = argparse.ArgumentParser()
    if sys.version_info < (3, 10):
        # https://bugs.python.org/issue9694
        ap._optionals.title = 'options'
    today = datetime.date.today()
    ap.add_argument('-L', dest='location', metavar='LOCATION', required=True)
    ap.add_argument('-d', dest='date', type=parse_date, default=today)
    options = ap.parse_args()
    loc = get_location(options.location)
    for i in [-1, 0, 1]:
        date = options.date + i * datetime.timedelta(1)
        def p(name, method):
            ts = method(date)
            ts = ts.replace(microsecond=0)
            if ts.date() == options.date:
                print(name, ts, sep='\t')
        p('midnight', loc.midnight)
        p('sunrise', loc.sunrise)
        p('noon', loc.noon)
        p('sunset', loc.sunset)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
