name: CI
on:
- push
- pull_request
jobs:
  main:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - python-version: '3.5'
          os: ubuntu-18.04
          astral-version: '1.3'
        python-version:
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10-dev'
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: run pydiatra
      run: |
        python3 -m pip install --user pydiatra
        python3 -m pydiatra .
    - name: run pyflakes
      run: |
        python3 -m pip install --user pyflakes
        python3 -m pyflakes .
    - name: check README syntax
      run: |
        python3 -m pip install --user pygments restructuredtext-lint
        rst-lint --level=info --encoding=UTF-8 README
    - name: install astral
      run: |
        v=${{matrix.astral-version}}
        python3 -m pip install astral${v:+==$v}
    - run: |
        prove -v

# vim:ts=2 sts=2 sw=2 et
